CREATE TYPE "AdminRole" AS ENUM ('SUPER_ADMIN', 'ADMIN');

ALTER TABLE "Admin"
ADD COLUMN "role" "AdminRole" NOT NULL DEFAULT 'SUPER_ADMIN';

ALTER TABLE "Admin"
ALTER COLUMN "role" SET DEFAULT 'ADMIN';
